name: Deploy VitePress site to Pages

on:
  push:
    branches: [vitepress]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: vitepress/pnpm-lock.yaml

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pnpm -C vitepress install

      - name: Build with VitePress
        run: pnpm -C vitepress docs:build

      - name: Run preview job on the background
        run: pnpm -C vitepress docs:preview &

      - name: Wait for the preview job
        uses: iFaxity/wait-on-action@v1.2.1
        with:
          resource: tcp:4173

      - name: Generate Library PDF
        run: |
          pnpm -C vitepress docs:print
          pkill -f docs:preview

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: vitepress/src/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
